version: '3'

services:
  image-converter:
    build: .
    container_name: simple-fast-image-converter
    image: treetips/simple-fast-image-converter
    env_file: settings.txt
    volumes:
      - ${WORKSPACE}:/images:rw
      - ./scripts:/tmp/scripts:ro
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    command: "python /tmp/scripts/converter.py"
